### ISSUE TITLE
Create nightly manager

### ISSUE THREAD

**Issue by oesteban** [templateflow/python-manager#4]
Write some code to run on circle or travis daily:

- Maintains S3 buckets in sync with the repo.
- Updates the root directory if there are changes in the subdatasets
- Updates the client's skeleton (and removes such responsibility from the client's CircleCI workflow)

Additionally, when a new release of the manager is cut:
- Cut a new release of the TF repository (https://github.com/templateflow/templateflow) by pushing a new annotated tag.
- Perhaps hit some endpoint to notify @yarikoptic's crawlers that a new release of `///templateflow` is ready?

**Comment by yarikoptic** [comment]
yeah, I am yet to establish auto updates/recrawling of some datasets for which I know that it should just work... this could be the first one to tackle.  Most likely to start with could be just a cron job on my end.   Since if there is no changes - there would be not much traffic, could probably just run it quite frequently (hourly?)

**Comment by oesteban** [comment]
hourly is way too much for templateflow - no traffic at all. But I guess that will allow you to check faster if things are okay.

**Comment by oesteban** [comment]
The three targets specified above are currently handled by GH-actions automations:

> * Maintains S3 buckets in sync with the repo.

- [x] [templateflow/templateflow](https://github.com/templateflow/templateflow/blob/b8d55dd58f27fe67a957557f25edaf2d0edeb2f6/.github/workflows/build-skeleton.yml#L144).

> * Updates the root directory if there are changes in the subdatasets

- [x] Done within [each template's repo](https://github.com/templateflow/tpl-MNIPediatricAsym/blob/a60c5463b76c6327e1cb9a460c86ce23f321918d/.github/workflows/update-superdataset.yml#L43-L46).

> * Updates the client's skeleton (and removes such responsibility from the client's CircleCI workflow)

- [x] [templateflow/templateflow](https://github.com/templateflow/templateflow/blob/b8d55dd58f27fe67a957557f25edaf2d0edeb2f6/.github/workflows/build-skeleton.yml#L79-L87).
